{{- $component := "analyzer" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "anchore-engine.analyzer.fullname" . }}"
  labels:
    app: "{{ template "anchore-engine.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ $component }}
spec:
  selector:
    matchLabels:
      app: "{{ template "anchore-engine.fullname" . }}"
      component: {{ $component }}
  replicas: {{ .Values.analyzer.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "anchore-engine.fullname" . }}"
        component: {{ $component }}
{{- if .Values.analyzer.annotations }}
      annotations:
{{ toYaml .Values.analyzer.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-{{ $component }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/anchore-manager"]
        args: ["service", "start", "analyzer"]
        envFrom:
        - secretRef:
            name: {{ template "anchore-engine.fullname" . }}
        - configMapRef:
            name: {{ template "anchore-engine.fullname" . }}
        env:
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: analyzer-api
          containerPort: {{ .Values.service.ports.analyzer }}
        volumeMounts:
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        {{- if .Values.global.internalServicesSslEnabled }}
        - name: certs
          mountPath: {{ default "/certs" .Values.analyzer.ssl.CertDir }}
          readOnly: true
        {{- end }}
        - name: analysis-scratch
          mountPath: {{ .Values.analyzer.analysisScratchVolume.mountPath }}
        livenessProbe:
          exec:
            command:
            - pgrep
            - twistd
          initialDelaySeconds: 10
          periodSeconds: 60
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: analyzer-api
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        resources:
{{ toYaml .Values.analyzer.resources | indent 10 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "anchore-engine.fullname" .}}
        {{- if .Values.global.internalServicesSslEnabled }}
        - name: certs
          secret:
            secretName: {{ .Values.analyzer.ssl.certSecret }}
        {{- end }}
        - name: analysis-scratch
          {{ toYaml .Values.analyzer.analysisScratchVolume.details -}}
    {{- if .Values.analyzer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.analyzer.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.analyzer.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.analyzer.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "anchore-engine.analyzer.fullname" . }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: anchore-analyzer-api
      port: {{ .Values.service.ports.analyzer }}
      targetPort: {{ .Values.service.ports.analyzer }}
      protocol: TCP
