{{- if or .Values.enterpriseFeeds.enabled .Values.enterpriseRbac.enabled -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "anchore-engine.enterprise.fullname" . }}"
  labels:
    app: "{{ template "anchore-engine.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |
    # Anchore Enterprise Service Configuration File

    # General system-wide configuration options, these should not need to
    # be altered for basic operation
    #
    service_dir: {{ .Values.global.configDir | quote }}
    tmp_dir: "/scratch"
    log_level: {{ .Values.global.logLevel | quote }}
    cleanup_images: true

    allow_awsecr_iam_auto: {{ .Values.global.allowECRUseIAMRole }}
    host_id: "${ANCHORE_POD_NAME}"
    internal_ssl_verify: {{ .Values.global.internalServicesSslVerifyCerts }}
    auto_restart_services: false
    license_file: "/license.yaml"

    metrics:
      enabled: {{ .Values.global.enableMetrics }}

    credentials:
      database:
        db_connect: 'postgresql+pg8000://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_HOST}:5432/${ANCHORE_DB_NAME}'
        db_connect_args:
          timeout: 120
          ssl: false
        db_pool_size: 30
        db_pool_max_overflow: 100

    services:
    {{- if .Values.enterpriseRbac.enabled }}
      # This should never be exposed outside of linked containers/localhost. It is used only for internal service access
      rbac_authorizer:
        enabled: true
        require_auth: true
        endpoint_hostname: localhost
        listen: '127.0.0.1'
        port: {{ .Values.enterpriseRbac.service.authPort }}
      rbac_manager:
        enabled: true
        require_auth: true
        endpoint_hostname: {{ template "anchore-engine.core.fullname" . }}
        listen: '0.0.0.0'
        port: {{ .Values.enterpriseRbac.service.apiPort }}
        authorization_handler: external
        authorization_handler_config:
          endpoint: 'http://localhost:{{ .Values.enterpriseRbac.service.authPort }}'
    {{- end }}
    {{- if .Values.enterpriseFeeds.enabled }}
      feeds:
        enabled: true
        require_auth: false
        endpoint_hostname: {{ template "anchore-engine.enterprise-feeds.fullname" . }}
        listen: '0.0.0.0'
        port: {{ .Values.enterpriseFeeds.service.apiPort }}
        # Time delay in seconds between consecutive driver runs for processing data
        cycle_timers:
          driver_sync: {{ .Values.enterpriseFeeds.cycle_timer_seconds }}
        # Staging space for holding normalized output from drivers.
        local_workspace: "{{ .Values.enterpriseFeeds.local_workspace }}"
        # Drivers process data from external sources and store normalized data in local_workspace. Processing large data sets
        # is a time consuming process for some drivers. To speed it up the container is shipped with pre-loaded data which is used
        # by default if local_workspace is empty.
        workspace_preload:
          # Do not use pre-loaded data if local_workspace is empty. Drivers will generate normalized data from scratch
          disabled: {{ .Values.enterpriseFeeds.workspace_preload_disabled }}
          # To load the workspace from a different location, uncomment and configure workspace_preload_file property to point to the tar.gz file
          workspace_preload_file: "{{ .Values.enterpriseFeeds.workspace_preload_file }}"
        # If api_only is set to True, the service will not update feed data in the system.
        # API end points will be functional and serve feed data if any is available.
        api_only: {{ .Values.enterpriseFeeds.api_only }}
        drivers:
          # Configuration section for drivers collecting and processing feed data.
          # All drivers are enabled by default unless explicitly disabled. npm and gem drivers are explicitly disabled out of the box
          npm:
            enabled: {{ .Values.enterpriseFeeds.npm_enabled }}
          gem:
            # rubygem data comes packaged as a PostgreSQL dump file. gem driver loads the pg dump and normalizes the data.
            # To enable gem driver comment the enabled property and uncomment the db_connect property. In addition,
            # uncomment the anchore-gem-db section in docker-compose.yaml
            enabled: {{ .Values.enterpriseFeeds.gem_enabled }}
            db_connect: {{ .Values.enterpriseFeeds.gem_db_connect }}
          centos:
            enabled: {{ .Values.enterpriseFeeds.centos_enabled }}
          debian:
            enabled: {{ .Values.enterpriseFeeds.debian_enabled }}
          ubuntu:
            enabled: {{ .Values.enterpriseFeeds.ubuntu_enabled }}
          ol:
            enabled: {{ .Values.enterpriseFeeds.ol_enabled }}
          alpine:
            enabled: {{ .Values.enterpriseFeeds.alpine_enabled }}
          snyk:
            enabled: {{ .Values.enterpriseFeeds.snyk_enabled }}
    {{- end }}
{{- end -}}
