{{- if .Values.enterpriseFeeds.enabled -}}
{{- $component := "enterprise-feeds" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "anchore-engine.enterprise-feeds.fullname" . }}"
  labels:
    app: "{{ template "anchore-engine.fullname" . }}"
    component: {{ $component }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: "{{ template "anchore-engine.fullname" . }}"
      component: {{ $component }}
  replicas: {{ .Values.enterpriseFeeds.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "anchore-engine.fullname" . }}"
        component: {{ $component }}
{{- if .Values.enterpriseFeeds.annotations }}
      annotations:
{{ toYaml .Values.enterpriseFeeds.annotations | indent 8 }}
{{- end }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "anchore-engine.enterprise.fullname" .}}
        - name: anchore-license
          secret:
            secretName: {{ .Values.enterpriseGlobal.licenseSecretName }}
      imagePullSecrets:
      - name: {{ .Values.enterpriseGlobal.imagePullSecretName }}
      containers:
      - name: {{ .Chart.Name }}-{{ $component }}
        image: "{{ .Values.enterpriseGlobal.image.repository }}:{{ .Values.enterpriseGlobal.image.tag }}"
        imagePullPolicy: {{ .Values.enterpriseGlobal.image.pullPolicy }}
        command: ["/usr/local/bin/anchore-enterprise-manager"]
        args: ["service", "start", "feeds"]
        ports:
        - containerPort: {{ .Values.enterpriseFeeds.service.apiPort }}
          name: feeds-api
        envFrom:
        - secretRef:
            name: {{ template "anchore-engine.fullname" . }}
        env:
        - name: ANCHORE_DB_HOST
          value: {{ template "postgres.feeds-db.fullname" . }}
        - name: ANCHORE_DB_NAME
          value: {{ index .Values "feeds-db" "postgresDatabase" | quote }}
        - name: ANCHORE_DB_USER
          value: {{ index .Values "feeds-db" "postgresUser" }}
        - name: ANCHORE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "anchore-engine.fullname" . }}
              key: .feedsDbPassword
        - name: ANCHORE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: config-volume
          mountPath: /config/config.yaml
          subPath: config.yaml
        - name: anchore-license
          mountPath: /license.yaml
          subPath: license.yaml
        readinessProbe:
          httpGet:
            path: /health
            port: feeds-api
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: feeds-api
          timeoutSeconds: 10
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 10
        resources:
{{ toYaml .Values.enterpriseFeeds.resources | indent 10 }}
    {{- if .Values.enterpriseFeeds.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.enterpriseFeeds.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.enterpriseFeeds.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.enterpriseFeeds.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "anchore-engine.enterprise-feeds.fullname" . }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ $component }}
spec:
  type: {{ .Values.enterpriseFeeds.service.type }}
  ports:
    - name: feeds-api
      port: {{ .Values.enterpriseFeeds.service.apiPort }}
      targetPort: {{ .Values.enterpriseFeeds.service.apiPort }}
      protocol: TCP
  selector:
    app: {{ template "anchore-engine.fullname" . }}
    component: {{ $component }}

{{- end -}}
