{{- if and .Values.anchoreEnterpriseGlobal.enabled (and .Values.anchoreEnterpriseUi.ingress.enabled .Values.anchoreEnterpriseUi.enabled) -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "anchore-engine.enterprise-ui.fullname" . }}"
  labels:
    app: "{{ template "anchore-engine.fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: enterprise-ui
{{- if .Values.anchoreEnterpriseUi.ingress.annotations }}
  annotations:
{{ toYaml .Values.anchoreEnterpriseUi.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.anchoreEnterpriseUi.ingress.tls }}
  tls:
  {{- range .Values.anchoreEnterpriseUi.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- if .Values.anchoreEnterpriseUi.ingress.hosts }}
  rules:
  {{- range .Values.anchoreEnterpriseUi.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.anchoreEnterpriseUi.ingress.path }}
            backend:
              serviceName: "{{ template "anchore-engine.enterprise-ui.fullname" $ }}"
              servicePort: {{ $.Values.anchoreEnterpriseUi.service.httpPort }}
  {{- end }}
{{- else }}
  backend:
    serviceName: {{ template "anchore-engine.enterprise-ui.fullname" . }}
    servicePort: {{ .Values.anchoreEnterpriseUi.service.httpPort }}
{{- end }}
{{- end -}}
