apiVersion: v1
kind: Secret
metadata:
  name: {{ template "anchore-engine.fullname" . }}
  labels:
    app: {{ template "anchore-engine.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  ANCHORE_ADMIN_PASSWORD: {{ .Values.anchoreGlobal.default_admin_password | quote }}
  ANCHORE_DB_PASSWORD: {{ index .Values "anchore-db" "postgresPassword" | quote }}
  {{- if and .Values.anchoreEnterpriseGlobal.enabled .Values.anchoreEnterpriseFeeds.enabled }}
  .feedsDbPassword: {{ index .Values "anchore-feeds-db" "postgresPassword" | quote }}
  {{- end }}
