dependencies:
  - name: postgresql
    version: "*"
    repository: "alias:stable"
    condition: postgresql.enabled
    alias: anchore-db

  - name: postgresql
    version: "*"
    repository: "alias:stable"
    condition: enterpriseConfig.ui.enabled
    alias: feeds-db

  - name: redis
    version: "*"
    repository: "alias:stable"
    condition: enterpriseConfig.ui.enabled
