dependencies:
  - name: postgresql
    version: "*"
    repository: "alias:stable"
    condition: postgresql.enabled

  - name: redis
    version: "*"
    repository: "alias:stable"
    condition: enterpriseConfig.ui.enabled
